version: '2'

services:
  app:
    image: 'weather-forecast:latest'
    build:
      context: .
    container_name: app
    ports:
        - 9091:9091
    depends_on:
      - elasticserver
          
  elasticserver:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.2'
    container_name: elasticserver
    ports:
        - 19200:9200
        - 19300:9300 
    environment:
      - node.name=ES01
      - discovery.type=single-node